from pathlib import Path


def replace_exact(path: str, old: str, new: str) -> None:
    file_path = Path(path)
    data = file_path.read_text(encoding="utf-8")
    count = data.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected exactly one anchor, found {count}")
    file_path.write_text(data.replace(old, new, 1), encoding="utf-8", newline="\n")


agents_anchor = """If the answers expose mixed ownership or a new responsibility, establish the boundary before expanding the feature implementation.\n\n#### Soft complexity triggers\n"""
agents_replacement = """If the answers expose mixed ownership or a new responsibility, establish the boundary before expanding the feature implementation.\n\n#### Recorded architecture pre-flight gate\n\nFor any substantial production edit that touches a protected/core handwritten file or a handwritten production source above roughly 1000 LOC, the architecture pre-flight **MUST be recorded before production editing begins**. The active implementation specification, audit, roadmap, or handoff must contain at least:\n\n```text\nArchitecture pre-flight:\n- current owner:\n- proposed responsibility:\n- authoritative state owner(s):\n- narrow typed input/output seam:\n- keep in current owner / extract:\n- reason:\n```\n\nIf this record is absent, substantial production editing is a stop condition until the pre-flight is completed. This is an execution gate, not a requirement to create a permanent standalone document for every micro-slice. Small bug fixes, mechanical edits, and already-approved implementation continuations do not require a new record unless they introduce or move responsibility.\n\n#### Soft complexity triggers\n"""
replace_exact("AGENTS.md", agents_anchor, agents_replacement)

audit_anchor = """6. fail closed when presentation-seat identity is absent, duplicated, out of range, or malformed.\n\nExisting `ClocktowerPairPlayerRevealPresentation` already establishes the correct architectural precedent: pair identity comes from typed data, never by parsing localized display text.\n"""
audit_replacement = """6. fail closed when presentation-seat identity is absent, duplicated, out of range, or malformed.\n\n### Sage architecture pre-flight — recorded before production edit\n\n```text\nArchitecture pre-flight:\n- current owner:\n  ClocktowerHostScreen currently owns both prepared Sage lifecycle facts and Sage-specific\n  pair recommendation/materialization; ClocktowerInformationStepBuilder owns generic\n  information-step reliability/selection mechanics; ClocktowerSageSquareTableUi owns\n  Sage square-table projection/rendering.\n- proposed responsibility:\n  Sage-specific pair candidate/recommendation projection, typed presentationSubjectSeats,\n  localized Sage display metadata, and Sage NightStep materialization.\n- authoritative state owner(s):\n  Host/session/canonical night flow remain authoritative for current Demon identity,\n  whether Sage actually died to the Demon this night, effective death-trigger ability state,\n  cards/seat order, and interaction ordering. The extracted owner must not recreate these facts.\n- narrow typed input/output seam:\n  prepared immutable Sage trigger actor + current Demon + resolved direct pair + effective\n  ability state + card roster, together with narrow recommendation/localization inputs,\n  -> ClocktowerDisplayOption / ClocktowerNightStepUi. No Host/session object dependency.\n- keep in current owner / extract:\n  EXTRACT to a role-local ClocktowerSageStepMaterializer owner.\n- reason:\n  Sage candidate construction, pair presentation identity, and step metadata form one cohesive\n  role-specific change unit. Keeping them in the protected >1000 LOC Host increases change\n  context radius and violates the Host growth rule. This does not reopen D6 and does not create\n  a one-materializer-per-role policy; other roles still require their own ownership audit.\n```\n\nBoundary constraints:\n\n- Host keeps death-trigger/current-Demon/effective-ability authority and only passes prepared facts;\n- `ClocktowerInformationStepBuilder` keeps generic reliable/unreliable/manual/automatic mechanics;\n- Sage materializer must not depend on the whole Host, screen, session, or a broad context object;\n- impaired Sage options remain `proposition = null`; typed seats are presentation-only;\n- global `clocktowerInformationCandidateId(...)` remains unchanged; Sage-local pair identity may include typed seats where required;\n- the extraction itself is behavior-preserving and does not justify unrelated role cleanup.\n\nExisting `ClocktowerPairPlayerRevealPresentation` already establishes the correct architectural precedent: pair identity comes from typed data, never by parsing localized display text.\n"""
replace_exact("docs/UI_R5_REMAINING_NIGHT_SURFACE_AUDIT_2026-09-10.md", audit_anchor, audit_replacement)
