package com.codex.campboardgamehost

import com.codex.campboardgamehost.clocktower.domain.DynamicInformationOutcome
import com.codex.campboardgamehost.clocktower.domain.RecommendationStyle
import com.codex.campboardgamehost.clocktower.domain.RoleId
import com.codex.campboardgamehost.clocktower.domain.StorytellerPhase
import com.codex.campboardgamehost.clocktower.epistemic.EpistemicObservationDraft
import com.codex.campboardgamehost.clocktower.epistemic.InformationProposition
import com.codex.campboardgamehost.clocktower.epistemic.NumericMetric
import com.codex.campboardgamehost.clocktower.epistemic.ObservationReliability
import com.codex.campboardgamehost.clocktower.epistemic.ObservationVisibility
import com.codex.campboardgamehost.clocktower.recommendation.dynamic.DynamicGenerationContext
import com.codex.campboardgamehost.clocktower.recommendation.dynamic.InformationReliability
import com.codex.campboardgamehost.clocktower.recommendation.dynamic.UnreliableNumberContext
import com.codex.campboardgamehost.clocktower.session.ClocktowerRecommendationCoordinator
import com.codex.campboardgamehost.clocktower.session.InformationDecisionRevision
import com.codex.campboardgamehost.clocktower.session.InformationResolutionRequest
import com.codex.campboardgamehost.clocktower.session.StructuredNumberInformationUiModel

/**
 * Role-neutral structured adapter for numeric Storyteller information.
 *
 * Numeric legality is generated by the existing Foundation candidate path from the supplied true
 * value, bounds and reliability. Recommendation identity marks a legal candidate as primary but
 * never changes which values are legal. Every confirmed value becomes the exact typed numeric
 * proposition that was shown to the player.
 */
internal fun prepareNumericInformationUiModel(
    coordinator: ClocktowerRecommendationCoordinator,
    gameId: String,
    phase: ClocktowerPhase,
    round: Int,
    sequence: Int,
    actorSeat: Int,
    abilityRole: RoleId,
    metric: NumericMetric,
    subjectSeats: List<Int>,
    trueValue: Int,
    minimumValue: Int,
    maximumValue: Int,
    reliability: InformationReliability,
    recommendationStyle: RecommendationStyle,
    revision: InformationDecisionRevision,
    recommendedValue: Int?,
    previousShownValue: Int? = null,
    pressureCostPerPoint: Int = 0,
): StructuredNumberInformationUiModel {
    require(actorSeat > 0) { "Numeric information actor seat must be positive." }
    require(subjectSeats.all { it > 0 } && subjectSeats.distinct().size == subjectSeats.size) {
        "Numeric information subject seats must be positive and unique."
    }
    require(minimumValue <= maximumValue) { "Numeric information bounds must be ordered." }
    require(trueValue in minimumValue..maximumValue) { "Numeric information truth must be within bounds." }

    val evaluations = coordinator.resolveNumberInformation(
        InformationResolutionRequest.Number(
            context = UnreliableNumberContext(
                trueValue = trueValue,
                minimumValue = minimumValue,
                maximumValue = maximumValue,
                previousShownValue = previousShownValue?.takeIf {
                    reliability != InformationReliability.RELIABLE && it in minimumValue..maximumValue
                },
                pressureCostPerPoint = pressureCostPerPoint,
            ),
            generation = DynamicGenerationContext(
                abilityRole = abilityRole,
                recipientSeat = actorSeat,
                reliability = reliability,
                style = recommendationStyle,
                targetSeats = subjectSeats.toSet(),
            ),
        ),
    )

    val effectiveRecommendedValue = recommendedValue
        ?: trueValue.takeIf { reliability == InformationReliability.RELIABLE }
    val recommendedIds = effectiveRecommendedValue?.let { value ->
        evaluations
            .filter { it.candidate.outcome.value == value }
            .mapTo(linkedSetOf()) { it.candidate.candidateId }
    }.orEmpty()
    val storytellerPhase = when (phase) {
        ClocktowerPhase.FirstNight -> StorytellerPhase.FIRST_NIGHT
        ClocktowerPhase.Dawn -> StorytellerPhase.DAWN
        ClocktowerPhase.Day -> StorytellerPhase.DAY
        ClocktowerPhase.Night -> StorytellerPhase.NIGHT
    }

    val context = coordinator.informationDecisionContext(
        evaluations = evaluations,
        recommendedCandidateIds = recommendedIds,
        revision = revision,
        semanticIdentity = "numeric|${abilityRole.value}|$gameId|${phase.name}|$round|$sequence|$actorSeat|${metric.name}",
        draftOf = { evaluation ->
            val value = evaluation.candidate.outcome.value
            val proposition = InformationProposition.NumericResult(
                metric = metric,
                sourceSeat = actorSeat,
                subjectSeats = subjectSeats,
                value = value,
            )
            EpistemicObservationDraft(
                recordId = clocktowerPrivateObservationRecordId(
                    gameId = gameId,
                    phase = phase,
                    round = round,
                    roleEnName = abilityRole.value,
                    actorSeat = actorSeat,
                    proposition = proposition,
                ),
                phase = storytellerPhase,
                round = round,
                sequence = sequence,
                sourceSeat = actorSeat,
                sourceAbility = abilityRole,
                visibility = ObservationVisibility.PRIVATE,
                recipientSeats = setOf(actorSeat),
                reliability = ObservationReliability.RECEIVED_AS_FUNCTIONING,
                proposition = proposition,
            )
        },
    )

    return StructuredNumberInformationUiModel.from(context)
}
